FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y build-essential llvm clang lld flex yacc bison bc qemu-system-x86 expect iwyu
ADD minified minified
ADD ./iwyu2 /usr/bin
RUN cd minified ; CC=iwyu2 LLVM=1 make tinyconfig ; LLVM=1 CC=iwyu2 make -j`nproc`
ADD Makefile Makefile
# RUN apt-get install screen -y
ADD vmtest.tcl vmtest.tcl
RUN CC=iwyu2 TERM=xterm make vm
