#!/usr/bin/env python3

'''
Wrapper script that first calls all argv as clang, then as iwyu
'''

import sys
import os
import subprocess

argv = sys.argv[1:]
subprocess.check_call(['clang'] + argv)
if not argv[-1].endswith('.S'):
    subprocess.check_call(['iwyu'] + argv)
