/*
 * Automatically generated file; DO NOT EDIT.
 * Linux/x86 5.19.0-rc8 Kernel Configuration
 */
#define CONFIG_ARCH_HAS_PTE_SPECIAL 1
#define CONFIG_BASE_SMALL 1
#define CONFIG_BINFMT_ELF 1
#define CONFIG_BLK_DEV_INITRD 1
#define CONFIG_BUILD_SALT ""
#define CONFIG_BUILDTIME_TABLE_SORT 1
#define CONFIG_CC_HAS_ASM_GOTO 1
#define CONFIG_CC_IMPLICIT_FALLTHROUGH "-Wimplicit-fallthrough"
#define CONFIG_CC_IS_CLANG 1
#define CONFIG_CC_OPTIMIZE_FOR_SIZE 1
#define CONFIG_CC_VERSION_TEXT "Debian clang version 19.1.7 (3+b1)"
#define CONFIG_CONSOLE_LOGLEVEL_DEFAULT 7
#define CONFIG_CPU_SUP_INTEL 1
#define CONFIG_DEFAULT_HOSTNAME "(none)"
#define CONFIG_DEFAULT_MMAP_MIN_ADDR 4096
#define CONFIG_DUMMY_CONSOLE 1
#define CONFIG_DUMMY_CONSOLE_COLUMNS 80
#define CONFIG_DUMMY_CONSOLE_ROWS 25
#define CONFIG_FRAME_WARN 1024
#define CONFIG_GENERIC_ENTRY 1
#define CONFIG_GENERIC_IRQ_PROBE 1
#define CONFIG_GENERIC_STRNLEN_USER 1
#define CONFIG_HW_CONSOLE 1
#define CONFIG_HZ 100
#define CONFIG_INIT_ENV_ARG_LIMIT 32
#define CONFIG_INITRAMFS_ROOT_GID 0
#define CONFIG_INITRAMFS_ROOT_UID 0
#define CONFIG_INITRAMFS_SOURCE "elo"
#define CONFIG_LD_ORPHAN_WARN 1
#define CONFIG_LTO_CLANG 1
#define CONFIG_MESSAGE_LOGLEVEL_DEFAULT 4
#define CONFIG_MMU 1
#define CONFIG_NR_CPUS 1
#define CONFIG_OUTPUT_FORMAT "elf32-i386"
#define CONFIG_PAGE_OFFSET 0xC0000000
#define CONFIG_PANIC_TIMEOUT 0
#define CONFIG_PGTABLE_LEVELS 2
#define CONFIG_PHYSICAL_ALIGN 0x10000
#define CONFIG_PHYSICAL_START 0x10000
#define CONFIG_RTC_LIB 1
#define CONFIG_SLUB 1
#define CONFIG_SPLIT_PTLOCK_CPUS 4
#define CONFIG_TINY_RCU 1
#define CONFIG_TINY_SRCU 1
#define CONFIG_VGA_CONSOLE 1
#define CONFIG_VT 1
#define CONFIG_X86_32 1
#define CONFIG_X86_INTERNODE_CACHE_SHIFT 4
#define CONFIG_X86_L1_CACHE_SHIFT 4
#define CONFIG_X86_MINIMUM_CPU_FAMILY 4
