#ifndef _UAPI_ASM_X86_DEBUGREG_H
#define _UAPI_ASM_X86_DEBUGREG_H

/* DR6 - debug status register */
#define DR6_RESERVED	(0xFFFF0FF0)
#define DR_TRAP0	(0x1)
#define DR_TRAP1	(0x2)
#define DR_TRAP2	(0x4)
#define DR_TRAP3	(0x8)
#define DR_TRAP_BITS	(DR_TRAP0|DR_TRAP1|DR_TRAP2|DR_TRAP3)
#define DR_BUS_LOCK	(0x800)
#define DR_STEP		(0x4000)
#define DR_GLOBAL_ENABLE_MASK (0xAA)
/* DR_SWITCH, DR_FIRSTADDR, DR_LASTADDR, DR_STATUS, DR_CONTROL,
   DR_CONTROL_SHIFT, DR_CONTROL_SIZE, DR_RW_*, DR_LEN_*,
   DR_LOCAL_*, DR_GLOBAL_SLOWDOWN, DR_GLOBAL_ENABLE, DR_ENABLE_SIZE,
   DR_CONTROL_RESERVED - unused */

#endif  
