# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the linux kernel.
#

obj-y     = fork.o panic.o \
	    cpu.o exit.o softirq.o \
	    user.o \
	    pid.o task_work.o \
	    extable.o params.o \
	    kthread.o sys_ni.o \
	    cred.o \
	    range.o

obj-y += sched/
obj-y += locking/
obj-y += printk/
obj-y += irq/
obj-y += rcu/
obj-y += entry/
obj-y += time/
