/* SPDX-License-Identifier: GPL-2.0 */
#ifndef _LINUX_TCP_STATES_H
#define _LINUX_TCP_STATES_H

enum {
	TCP_ESTABLISHED = 1,
	TCP_SYN_SENT,
	TCP_SYN_RECV,
	TCP_FIN_WAIT1,
	TCP_FIN_WAIT2,
	TCP_TIME_WAIT,
	TCP_CLOSE,
	TCP_CLOSE_WAIT,
	TCP_LAST_ACK,
	TCP_LISTEN,
	TCP_CLOSING,	/* Now a valid state */
	TCP_NEW_SYN_RECV,

	TCP_MAX_STATES	/* Leave at the end! */
};

#define TCPF_ESTABLISHED	(1 << TCP_ESTABLISHED)
#define TCPF_SYN_SENT		(1 << TCP_SYN_SENT)
#define TCPF_SYN_RECV		(1 << TCP_SYN_RECV)
#define TCPF_FIN_WAIT1		(1 << TCP_FIN_WAIT1)
#define TCPF_FIN_WAIT2		(1 << TCP_FIN_WAIT2)
#define TCPF_TIME_WAIT		(1 << TCP_TIME_WAIT)
#define TCPF_CLOSE		(1 << TCP_CLOSE)
#define TCPF_CLOSE_WAIT		(1 << TCP_CLOSE_WAIT)
#define TCPF_LAST_ACK		(1 << TCP_LAST_ACK)
#define TCPF_LISTEN		(1 << TCP_LISTEN)
#define TCPF_CLOSING		(1 << TCP_CLOSING)
#define TCPF_NEW_SYN_RECV	(1 << TCP_NEW_SYN_RECV)

#endif	/* _LINUX_TCP_STATES_H */