# SPDX-License-Identifier: GPL-2.0
obj-y += entry/

obj-$(CONFIG_PERF_EVENTS) += events/

# Xen paravirtualization support

obj-y += realmode/
obj-y += kernel/
obj-y += mm/

# for cleaning
subdir- += boot tools
