# SPDX-License-Identifier: GPL-2.0

# mapping.o merged into drivers/base/core.c
obj-$(CONFIG_DMA_OPS)			+= ops_helpers.o
obj-$(CONFIG_DMA_OPS)			+= dummy.o
obj-$(CONFIG_DMA_CMA)			+= contiguous.o
obj-$(CONFIG_DMA_DECLARE_COHERENT)	+= coherent.o
obj-$(CONFIG_DMA_API_DEBUG)		+= debug.o
obj-$(CONFIG_SWIOTLB)			+= swiotlb.o
obj-$(CONFIG_DMA_COHERENT_POOL)		+= pool.o
obj-$(CONFIG_DMA_MAP_BENCHMARK)		+= map_benchmark.o
