/* Minimal ioctls.h - only keep ioctls actually used */
#ifndef __ASM_GENERIC_IOCTLS_H
#define __ASM_GENERIC_IOCTLS_H

#include <linux/ioctl.h>

/* Used by tty_io.c */
#define TIOCSPGRP	0x5410
#define TIOCGWINSZ	0x5413
#define TIOCSWINSZ	0x5414

/* Used as aliases/referenced */
#define FIONREAD	0x541B
#define TIOCINQ		FIONREAD
#define TIOCOUTQ	0x5411


/* Unused ioctls removed:
 * TCGETS, TCSETS, TCSETSW, TCSETSF, TCGETA, TCSETA, TCSETAW, TCSETAF
 * TCSBRK, TCXONC, TCFLSH, TIOCEXCL, TIOCNXCL, TIOCSCTTY, TIOCGPGRP
 * TIOCSTI, TIOCMGET, TIOCMBIS, TIOCMBIC, TIOCMSET, TIOCGSOFTCAR
 * TIOCSSOFTCAR, TIOCLINUX, TIOCCONS, TIOCGSERIAL, TIOCSSERIAL
 * TIOCPKT, FIONBIO, TIOCNOTTY, TIOCSETD, TIOCGETD, TCSBRKP
 * TIOCSBRK, TIOCCBRK, TIOCGSID, TCGETS2, TCSETS2, TCSETSW2, TCSETSF2
 * TIOCSERCONFIG
 */

#endif
