# SPDX-License-Identifier: GPL-2.0
#
# Headers that are mandatory in usr/include/asm/
# (This file is not included when SRCARCH=um since UML does not support UAPI.)

mandatory-y += bitsperlong.h
mandatory-y += errno.h
mandatory-y += mman.h
mandatory-y += param.h
mandatory-y += posix_types.h
mandatory-y += ptrace.h
mandatory-y += setup.h
mandatory-y += signal.h
mandatory-y += types.h
