# SPDX-License-Identifier: GPL-2.0
hostprogs-always-$(CONFIG_BUILDTIME_TABLE_SORT)		+= sorttable
HOSTCFLAGS_sorttable.o = -I$(srctree)/tools/include
HOSTLDLIBS_sorttable = -lpthread
subdir-	+= basic dtc kconfig mod
