#!/bin/sh
# SPDX-License-Identifier: GPL-2.0

TARGET=$1
ARCH=$2
CC_VERSION="$3"
LD=$4

set -f
LC_ALL=C
export LC_ALL

VERSION=$(cat .version 2>/dev/null || echo 1)
TIMESTAMP=`date`
LINUX_COMPILE_BY=$(whoami | sed 's/\\/\\\\/')
LINUX_COMPILE_HOST=`uname -n`

UTS_LEN=64
UTS_VERSION="$(echo "#$VERSION" $TIMESTAMP | cut -b -$UTS_LEN)"

# Generate a temporary compile.h
{ echo /\* This file is auto generated, version $VERSION \*/
  echo \#define UTS_MACHINE \"$ARCH\"
  echo \#define UTS_VERSION \"$UTS_VERSION\"
  printf '#define LINUX_COMPILE_BY "%s"\n' "$LINUX_COMPILE_BY"
  echo \#define LINUX_COMPILE_HOST \"$LINUX_COMPILE_HOST\"
  LD_VERSION=$($LD -v | head -n1 | sed 's/(compatible with [^)]*)//' \
		      | sed 's/[[:space:]]*$//')
  printf '#define LINUX_COMPILER "%s"\n' "$CC_VERSION, $LD_VERSION"
} > .tmpcompile

# Only replace if content changed (ignoring timestamp in UTS_VERSION)
if [ -r $TARGET ] && \
      grep -v UTS_VERSION $TARGET > .tmpver.1 && \
      grep -v UTS_VERSION .tmpcompile > .tmpver.2 && \
      cmp -s .tmpver.1 .tmpver.2; then
   rm -f .tmpcompile
else
   echo "  UPD     $TARGET"
   mv -f .tmpcompile $TARGET
fi
rm -f .tmpver.1 .tmpver.2
