#ifndef _LINUX_ERRNO_H
#define _LINUX_ERRNO_H
#include <asm/errno.h>
#define ERESTARTSYS 512
#define ERESTARTNOINTR 513
#define ERESTARTNOHAND 514
#define ENOIOCTLCMD 515
#define ERESTART_RESTARTBLOCK 516
#define EPROBE_DEFER 517
#define EOPENSTALE 518
#define ENOPARAM 519
#define EIOCBQUEUED 529
#endif
