#ifndef _LINUX_POISON_H
#define _LINUX_POISON_H


# define POISON_POINTER_DELTA 0

#define LIST_POISON1  ((void *) 0x100 + POISON_POINTER_DELTA)
#define LIST_POISON2  ((void *) 0x122 + POISON_POINTER_DELTA)

#define TIMER_ENTRY_STATIC	((void *) 0x300 + POISON_POINTER_DELTA)

#define TAIL_MAPPING	((void *) 0x400 + POISON_POINTER_DELTA)

#define POISON_FREE_INITMEM	0xcc

/* Removed unused poison defines: PAGE_POISON, RED_INACTIVE, RED_ACTIVE,
   POISON_INUSE, POISON_FREE, POISON_END, JBD_POISON_FREE, JBD2_POISON_FREE,
   POOL_POISON_FREED, POOL_POISON_ALLOCATED, ATM_POISON_FREE, ATM_POISON,
   MUTEX_DEBUG_INIT, MUTEX_DEBUG_FREE, MUTEX_POISON_WW_CTX, KEY_DESTROY, PP_SIGNATURE */

#endif
