#ifndef VM_EVENT_ITEM_H_INCLUDED
#define VM_EVENT_ITEM_H_INCLUDED

/* Minimal vm_event_item - only items actually used in .c files */
#define FOR_ALL_ZONES(xx) xx##_NORMAL, xx##_MOVABLE

enum vm_event_item {
	FOR_ALL_ZONES(PGALLOC),
	PGFREE, PGACTIVATE, PGDEACTIVATE, PGLAZYFREE,
	PGFAULT, PGREUSE, PGROTATED,
	UNEVICTABLE_PGCULLED, UNEVICTABLE_PGRESCUED, UNEVICTABLE_PGCLEARED,
	NR_VM_EVENT_ITEMS
};

#endif		 
